Jenkinsfile
Related to camunda-internal/gcloud-infrastructure#10
=> chore(jenkins): Add Jenkinsfile

src/pages/toolkit/bpmn-js/walkthrough/walkthrough.md
While I was reading the walkthrough page, I found that there was some dead links/anchors. Here's a little fix for it. 😄
=> Fixing dead links/anchors.

src/pages/toolkit/bpmn-js/walkthrough/walkthrough.md
Fixed some minor typos in the documentation
=> fix(walkthrough): fixed typos

src/blog/2018/012-bpmnlint.md
* I accidentally merged the PR before my commit was pushed
=> chore(blog): fix typos in bpmnlint blog post

src/pages/jobs/index.hbs
=> fix(pages/jobs): link to workable

src/pages/toolkit/bpmn-js/walkthrough/walkthrough.md
Hello, thought I'd contribute some improvements and fixes while reading the bpmn-js walkthrough.
Happy to make any necessary changes or follow-up commits.
There was one minor thing I wasn't quite sure of. Details in commit body of c7f7d89.
=> Improve bpmn-js walkthrough docs

src/pages/about/index.hbs
=> chore(about): update team

src/blog/2019/001-sketchy-is-the-new-default.md, src/blog/2019/003-html-injection-vulnerabilities-fixed.md, src/blog/2019/005-html-injection-vulnerabilities-fixed-properties-panels.md
=> 58 propsprops

src/pages/toolkit/bpmn-js/walkthrough/walkthrough.md
change
<link rel="stylesheet" href="bpmn-js/dist/assets/bpmn-font/css/bpmn-.css" />
to
<link rel="stylesheet" href="bpmn-js/dist/assets/bpmn-font/css/bpmn.css" />
=> stylesheet href is wrong

src/blog/2020/001-dmn-js-8.md
=> feat(blog): add dmn-js@8 blog post

src/links/moving-to-promises.html
Related to https://github.com/bpmn-io/bpmn.io/issues/71
=> chore(links): add link to promises example

src/pages/status/index.hbs
This migrates repo to travis-ci.com.
=> chore(project): migrate to travis-ci.com

src/pages/about/index.hbs
__Which issue does this PR address?__
Closes #77
__Acceptance Criteria__
__Definition of Done__
=> Added Alexis and Max to team members, moved Oǧuz to former members

src/pages/toolkit/bpmn-js/walkthrough/walkthrough.md
This PR converts the bpmn-js walkthrough to ES6 via arrow functions and async/await promise handling.
It also fixes outdated paths.
=> Update walkthrough document

package-lock.json, src/pages/about/index.hbs
__Which issue does this PR address?__
This was identified by Marketing. The term "CamBPM" is outdated and shall be removed.
__Acceptance Criteria__
__Definition of Done__
=> Remove cam bpm term

src/pages/legal/terms.hbs
Hello @nikku,
this is just a small contribution (small fix typo).
Have a nice day and keep going 🚀
=> ✏️ fix typo

src/blog/2020/004-bpmn-js-promisified.md, src/blog/2021/004-dmn-js-promisified.md
closes bpmn-io/internal-docs#299
=> Add dmn js promisification blog

.github/workflows/MERGE_MASTER_TO_LIVE.yml
Related to https://github.com/bpmn-io/fake-join/issues/35
=> ci: automatically create PR to merge master to live

Gruntfile.js, app.js, package-lock.json, package.json, server.js
With recent changes we removed our dev setup, cf. https://github.com/bpmn-io/bpmn.io/commit/11fceea29fe4e44cecc9b526a094bc01390687d8#r52864628.
This PR restores it.
=> Restore dev setup

.github/workflows/CI.yml
=> ci: add GitHub Action

.github/workflows/PRODUCTION.yml, .github/workflows/STAGING.yml
Closes #91
Tested on staging via https://github.com/bpmn-io/bpmn.io/runs/3382912255?check_suite_focus=true
=> Deploy websites with GitHub Actions

.github/workflows/PRODUCTION.yml, .github/workflows/STAGING.yml
This works: https://github.com/bpmn-io/bpmn.io/runs/3397684727?check_suite_focus=true
=> ci: deploy websites with GitHub Actions

src/templates/layouts/blogpost.hbs
=> Removed "share with Google Plus" button in blogs

src/pages/about/index.hbs
=> chore: update contributors on about page

src/pages/about/index.hbs
This adds Martin to the contributor list
=> chore: update contributors

.github/workflows/PRODUCTION.yml, .github/workflows/STAGING.yml, Gruntfile.js, src/blog/2021/001-chor-js.md, src/blog/2021/002-wasdenn-modeling-assistant.md, src/blog/2021/003-form-js-visual-form-editing-and-embedding.md, src/blog/2021/005-bpmn-js-visual-workflow-configuration-in-bubblz.md, src/blog/2021/006-2021-year-in-review.md, src/blog/2022/001-form-js-0-6-0.md, src/blog/2022/002-bpmn-js-9-0-0.md, src/blog/2022/003-form-js-0.7.0.md, src/blog/2022/004-bpmn-js-nft.md, src/helpers/helper-appUrl.js, src/templates/layouts/bare.hbs
+ `appUrl` helper
+ minor meta-data improvements
=> Add `appUrl` helper to simplify location of preview images and friends

.github/workflows/PRODUCTION.yml, .github/workflows/STAGING.yml, Gruntfile.js, src/blog/2021/001-chor-js.md, src/blog/2021/002-wasdenn-modeling-assistant.md, src/blog/2021/003-form-js-visual-form-editing-and-embedding.md, src/blog/2021/005-bpmn-js-visual-workflow-configuration-in-bubblz.md, src/blog/2021/006-2021-year-in-review.md, src/blog/2022/001-form-js-0-6-0.md, src/blog/2022/002-bpmn-js-9-0-0.md, src/blog/2022/003-form-js-0.7.0.md, src/blog/2022/004-bpmn-js-nft.md, src/data/site.yml, src/helpers/feed/helper-rssDate.js, src/helpers/feed/helper-rssPost.js, src/helpers/feed/rssDate.js, src/helpers/helper-appUrl.js, src/helpers/helper-changelogRef.js, src/pages/feed.hbs, src/pages/releases.hbs, src/pages/toolkit/bpmn-js/index.hbs, src/pages/toolkit/cmmn-js/index.hbs, src/pages/toolkit/dmn-js/index.hbs, src/pages/toolkit/form-js/index.hbs, src/templates/layouts/bare.hbs, src/templates/layouts/blogpost_fooled.hbs
_Adds an RSS feed for blog contents and library releases:_
Why not, it is 2022! :slightly_smiling_face:.
---
Also links to the CHANGELOG of each libraries latest release:
---
Builds on top of https://github.com/bpmn-io/bpmn.io/pull/126
Closes https://github.com/bpmn-io/bpmn.io/issues/122
=> Add a RSS feed (blog updates + releases)

src/templates/partials/footer.hbs
=> chore: update footer notice date

src/pages/about/index.hbs
=> Update contributors and links to camunda.com on about page

src/blog/2022/009-es2018.md
=> fix: correct slug

src/assets/less/_style.less, src/blog/2023/002-bpmn-js-create-append-anything.md, src/pages/toolkit/bpmn-js/walkthrough/walkthrough.md
It externalizes create/append anything (again).
=> Add bpmn-js@12 migration note

src/templates/partials/about_teaser.hbs
Related to https://github.com/camunda/product-hub/issues/1560
=> chore: replace Camunda Platform with Camunda

src/templates/layouts/base.hbs
We're in the middle of the conference soon.
=> chore: remove CCon banner

src/templates/partials/footer.hbs
=> chore: update copy year

.github/workflows/PRODUCTION.yml, .github/workflows/STAGING.yml
Related to https://github.com/bpmn-io/internal-docs/issues/839
=> ci: deploy to netlify

src/pages/about/index.hbs
:wave: + have a great time :heart_eyes:
=> chore(about): make Niklas a past member

src/pages/about/index.hbs
Moved Christian Konrad back to contributor at his request. He will still contribute.
=> feat(about)-move-Christian

src/blog/2014/001-announcing-bpmn-io.md, src/blog/2015/005-revamped-modeling-interaction.md, src/blog/2015/006-collaborations-message-flows.md, src/blog/2015/007-bpmn-desktop-app.md, src/blog/2015/012-lanes-data-objects.md, src/blog/2015/013-bpmn-properties-panel.md, src/blog/2016/001-dmn-js-0-4.md, src/blog/2016/002-properties-panel-0-5.md, src/blog/2016/003-bpmn-js-0-13.md, src/blog/2016/004-properties-panel-0-6.md, src/blog/2016/006-bpmn-js-0-14.md, src/blog/2016/007-dmn-js-0-5.md, src/blog/2016/008-cmmn-js-0-3.md, src/blog/2016/009-cmmn-js-0-4.md, src/blog/2016/010-cmmn-js-0-5-1.md, src/blog/2016/016-dmn-js-0-8.md, src/blog/2016/018-cmmn-js-0.7.md
Closes https://github.com/bpmn-io/internal-docs/issues/758.
=> fix(blog): remove :skull: Twitter references

src/blog/2023/002-bpmn-js-create-append-anything.md
The link will otherwise not point to the changelog.
=> fix: correct bpmn-js version

src/pages/index.hbs
Try to save on our bandwidth.
----
Related to https://github.com/bpmn-io/internal-docs/issues/953
=> chore: serve heavy static assets via CDN

src/templates/layouts/base.hbs, src/templates/partials/ccon_banner.hbs
=> feat: add CCon banner

src/templates/partials/about_teaser.hbs
=> feat: update Camunda signup link

src/pages/about/index.hbs
=> chore: make Christian a past member

src/pages/about/index.hbs
=> chore: add Jarek Danielak

src/data/site.yml, src/pages/about/index.hbs
=> Update members list and libraries versions

src/templates/layouts/base.hbs, src/templates/partials/ccon_banner.hbs
This supports CamundaCon NY marketing ([ref](https://app.asana.com/0/1207406464318213/1207917487832022)).
Changes are in line with prior communications.
=> feat: add CamundaCon NY banner

src/templates/layouts/base.hbs
Banner (https://github.com/bpmn-io/bpmn.io/pull/202) should only be active for two weeks. 
=> Remove CamundaCon NYC banner

src/templates/partials/gtm_body.hbs, src/templates/partials/gtm_header.hbs
Related to https://github.com/bpmn-io/internal-docs/issues/1049
This migrates the website to Camunda-owned domain as planned.
=> chore: migrate to server-side GTM

.github/workflows/CI.yml, .github/workflows/PRODUCTION.yml, .github/workflows/STAGING.yml
Follows along our recent move to make job names `snake_case`.
=> ci: make job names `snake_case`

src/blog/2024/005-bpmn-js-17-0-0.md
This announces ("retrofits") the major breaking change 17.0.0 bpmn-js release:
Related to https://github.com/bpmn-io/diagram-js/issues/796
=> feat(blog): add remove touch integration support

src/pages/about/index.hbs
Adding Balazs as a team member.
=> Adding Balazs-PM as a team member.

src/blog/2025/002-ditching-the-xml-in-bpmn.md
Mark our recent blog according to our post April 1st policy:
=> chore(blog): mark XML blog accordingly

src/templates/partials/ccon_banner.hbs
Changes from in person to virtual promotion, as specified [here](https://app.asana.com/1/384886434863350/task/1209910569241785/comment/1210045418500980?focus=true).
=> feat: update CCon banner

src/templates/layouts/base.hbs, src/templates/partials/ccon_banner.hbs
Undoes https://github.com/bpmn-io/bpmn.io/pull/212, removing the CCon banner again:
To be done May 15th, specified [here](https://app.asana.com/0/1208716972734912/1209910569241785).
=> feat: remove banner for CCon 2025 Amsterdam
